# Generated by Django 6.0.6 on 2026-06-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('maintenance', 'تعمیرات'), ('cleaning', 'نظافت'), ('item', 'کالا'), ('booth', 'غرفه')], max_length=20, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('ai_content_flag', models.BooleanField(blank=True, null=True, verbose_name='پرچم محتوای هوش مصنوعی')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست رسیدگی\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کالای انبار',
                'verbose_name_plural': 'کالاهای انبار',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='BoothRequest',
            fields=[
                ('requestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_app.requestbase')),
                ('name', models.CharField(max_length=200, verbose_name='نام غرفه یا کسب\u200cوکار')),
                ('category', models.CharField(max_length=100, verbose_name='نوع کالا یا خدمات')),
                ('event_date', models.DateField(verbose_name='تاریخ رویداد')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
            ],
            options={
                'verbose_name': 'درخواست غرفه',
                'verbose_name_plural': 'درخواست\u200cهای غرفه',
            },
            bases=('requests_app.requestbase',),
        ),
        migrations.CreateModel(
            name='CleaningRequest',
            fields=[
                ('requestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_app.requestbase')),
                ('location', models.CharField(max_length=200, verbose_name='محل')),
                ('preferred_date', models.DateField(verbose_name='تاریخ ترجیحی')),
                ('extra_description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'درخواست نظافت',
                'verbose_name_plural': 'درخواست\u200cهای نظافت',
            },
            bases=('requests_app.requestbase',),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('requestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_app.requestbase')),
                ('location', models.CharField(max_length=200, verbose_name='محل')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='تصویر')),
                ('extra_description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'درخواست تعمیرات',
                'verbose_name_plural': 'درخواست\u200cهای تعمیرات',
            },
            bases=('requests_app.requestbase',),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('requestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_app.requestbase')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('delivery_status', models.CharField(blank=True, max_length=100, verbose_name='وضعیت تحویل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='requests_app.inventoryitem', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'درخواست کالا',
                'verbose_name_plural': 'درخواست\u200cهای کالا',
            },
            bases=('requests_app.requestbase',),
        ),
        migrations.AddIndex(
            model_name='requestbase',
            index=models.Index(fields=['user'], name='requests_ap_user_id_5d5d67_idx'),
        ),
        migrations.AddIndex(
            model_name='requestbase',
            index=models.Index(fields=['status'], name='requests_ap_status_9b25c0_idx'),
        ),
        migrations.AddIndex(
            model_name='requestbase',
            index=models.Index(fields=['created_at'], name='requests_ap_created_2509a7_idx'),
        ),
        migrations.AddIndex(
            model_name='requestbase',
            index=models.Index(fields=['handled_by'], name='requests_ap_handled_402c71_idx'),
        ),
    ]
