# Generated by Django 6.0.6 on 2026-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_request_status_history_and_supervisor_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestbase',
            new_name='requests_ap_assigne_24443d_idx',
            old_name='requests_ap_assigne_6e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='requeststatushistory',
            new_name='requests_ap_request_5ee6b5_idx',
            old_name='requests_ap_request_0a8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='requeststatushistory',
            new_name='requests_ap_acting__1518af_idx',
            old_name='requests_ap_acting__f3c1d4_idx',
        ),
    ]
