# Generated by Django 6.0.6 on 2026-06-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بلوک')),
                ('total_floors', models.PositiveIntegerField(verbose_name='تعداد طبقات')),
                ('room_numbers', models.JSONField(verbose_name='شماره اتاق\u200cها')),
            ],
            options={
                'verbose_name': 'بلوک',
                'verbose_name_plural': 'بلوک\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='شماره اتاق')),
                ('floor', models.PositiveIntegerField(verbose_name='طبقه')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dorms.block', verbose_name='بلوک')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['block', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField(verbose_name='تاریخ شروع')),
                ('assigned_to', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=True, verbose_name='فعال')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dorms.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تخصیص اتاق',
                'verbose_name_plural': 'تخصیص\u200cهای اتاق',
                'ordering': ['-assigned_from'],
            },
        ),
    ]
