# Generated by Django 6.0.6 on 2026-06-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['user'], name='dorms_rooma_user_id_148f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['room'], name='dorms_rooma_room_id_3807e0_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['is_current'], name='dorms_rooma_is_curr_6ae2d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_active_room_assignment_per_user'),
        ),
    ]
