# Generated by Django 6.0.6 on 2026-06-16 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان')),
                ('category', models.CharField(choices=[('educational', 'آموزشی'), ('sports', 'ورزشی'), ('cultural', 'فرهنگی'), ('art', 'هنری')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت\u200cنام')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='لغو شده')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('class_instance', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='classes.class', verbose_name='کلاس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام کلاس',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای کلاس',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['user'], name='classes_cla_user_id_774d3b_idx'), models.Index(fields=['class_instance'], name='classes_cla_class_i_80ea13_idx'), models.Index(fields=['is_cancelled'], name='classes_cla_is_canc_d27e15_idx')],
                'unique_together': {('user', 'class_instance')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('class_instance', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='classes.class', verbose_name='کلاس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='classes_rat_user_id_6c6f23_idx'), models.Index(fields=['class_instance'], name='classes_rat_class_i_3e8d66_idx')],
                'unique_together': {('user', 'class_instance')},
            },
        ),
    ]
