# Generated by Django 6.0.6 on 2026-06-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('suggestion', 'پیشنهاد'), ('idea', 'ایده'), ('complaint', 'شکایت')], max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('reviewed', 'بررسی شده'), ('answered', 'پاسخ داده شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('supervisor_response', models.TextField(blank=True, verbose_name='پاسخ سرپرست')),
                ('upvotes', models.IntegerField(default=0, verbose_name='رأی مثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_complaints', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ایده / شکایت',
                'verbose_name_plural': 'ایده\u200cها و شکایات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'موافق'), ('down', 'مخالف')], max_length=10, verbose_name='نوع رأی')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رأی')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.ideacomplaint', verbose_name='ایده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رأی',
                'verbose_name_plural': 'آراء',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ideacomplaint',
            index=models.Index(fields=['user'], name='ideas_ideac_user_id_f3af8a_idx'),
        ),
        migrations.AddIndex(
            model_name='ideacomplaint',
            index=models.Index(fields=['status'], name='ideas_ideac_status_a7d363_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='ideas_vote_user_id_26b5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['idea'], name='ideas_vote_idea_id_369cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'idea')},
        ),
    ]
