# Generated by Django 6.0.6 on 2026-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_supervisor_feedback_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ideacomplaint',
            new_name='ideas_ideac_type_d787bd_idx',
            old_name='ideas_ideac_type_8f1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='ideacomplaint',
            new_name='ideas_ideac_categor_64964b_idx',
            old_name='ideas_ideac_categor_4c3d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='ideacomplaint',
            new_name='ideas_ideac_created_a6ec17_idx',
            old_name='ideas_ideac_created_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='ideacomplaint',
            new_name='ideas_ideac_respond_e805c8_idx',
            old_name='ideas_ideac_respond_5d4e3f_idx',
        ),
    ]
